CREATE SCHEMA IF NOT EXISTS unimdb;

-- ----------------------------
-- Table unimdb.user
-- ----------------------------

CREATE TABLE IF NOT EXISTS unimdb.user (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR (50) NOT NULL ,
    middle_name VARCHAR (50) NOT NULL ,
    last_name VARCHAR (50) NOT NULL ,
    username VARCHAR (50) NOT NULL ,
    phone_number VARCHAR (15) NOT NULL ,
    email VARCHAR (50) ,
    password_hash VARCHAR (32) NOT NULL ,
    registered_at timestamp ,
    last_login timestamp ,
    intro TEXT ,
    profile TEXT,
    PRIMARY KEY(id));


-- ----------------------------
-- Table unimdb.user_posts
-- ----------------------------

CREATE TABLE IF NOT EXISTS unimdb.user_posts (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    message TEXT NULL ,
    created_at TIMESTAMP ,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_user_posts1
    FOREIGN KEY (user_id)
        REFERENCES unimdb.user(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION);

CREATE INDEX fk_user_user_posts1_idx ON unimdb.user_posts(user_id);