ALTER TABLE unimdb.localized_interests
DROP CONSTRAINT localized_interests_pkey;

ALTER TABLE unimdb.localized_universities
DROP CONSTRAINT localized_universities_pkey;

ALTER TABLE unimdb.localized_faculties
DROP CONSTRAINT localized_faculties_pkey;